### ISSUE TITLE
What is the difference between `math_test.cpp` and `math_test_custom.cpp` examples? 

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/sharedlibpp#1]
At a first glance I was not able to get the substantial difference between the two. Any insight @drdanz @diegoferigo @apaikan ?

**Comment by drdanz** [comment]
I made some changes in order to support a different "start" and "end" checks, since YARP uses the "YARP" vocab, but the library used "SHPP", and I would like to keep the old plugins compatible...

The "custom" examples uses a custom string, while the "normal" example uses the default string...
