### ISSUE TITLE
Size of void*

### ISSUE THREAD

**Issue by IngwiePhoenix** [robotology-playground/sharedlibpp#3]
I would like to know why in this line:

https://github.com/robotology-playground/sharedlibpp/blob/master/src/shlibpp/config.h.in#L12

You can not just use `sizeof(void*)`?

**Comment by traversaro** [comment]
Good point. Any idea @drdanz ?

**Comment by drdanz** [comment]
Good catch!

That's something that was inherited from a long long time ago (see robotology/yarp@9d0aeb9f841143e9c0cf138dc43eb4aed415e735)... I don't know if there was a reason for that at the time. The only reason I could think about is that there might have been some tentative to load plugins compiled on 32 bit, from a 64 bit build.

I don't think it's going to work anyway, we can probably replace it, and get rid of the `config.h.in` file...

**Comment by drdanz** [comment]
Any volounteer? :grimacing:

**Comment by IngwiePhoenix** [comment]
@drdanz Calling between 32bit and 64 bit is rather difficult since their memory alignment are quite different, obviously. So using `sizeof(void*)` should probably do.

Seeing as to how a 64bit Linux installation is "not liking" to run 32bit software and how Windows does not seem to handle loading a 32bit dll in a 64bit application so well, I would bet that it is safe to say - albeit probably not impossible - that this library may target either 32bit OR 64bit, depending on it's compilation.
